WITH TOTAL_SALES AS (
    SELECT
        B.AUTHOR_ID,
        B.CATEGORY,
        SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
    FROM
        BOOK_SALES BS
    JOIN
        BOOK B ON B.BOOK_ID = BS.BOOK_ID
    WHERE
        TO_CHAR(BS.SALES_DATE, 'YYYY-MM') = '2022-01'
    GROUP BY
        B.AUTHOR_ID, B.CATEGORY
)

SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    TS.CATEGORY,
    TS.TOTAL_SALES
FROM
    AUTHOR A
JOIN
    TOTAL_SALES TS ON A.AUTHOR_ID = TS.AUTHOR_ID
ORDER BY
    A.AUTHOR_ID, TS.CATEGORY DESC;