SELECT
    ID,
    (SELECT COUNT(*)
     FROM ECOLI_DATA
     WHERE PARENT_ID = ED.ID) AS 'CHILD_COUNT'
FROM
    ECOLI_DATA ED
ORDER BY ID;

# SELECT
#     ID,
#     IFNULL((SELECT COUNT(*)
#             FROM ECOLI_DATA
#             GROUP BY PARENT_ID
#             HAVING PARENT_ID = ID), 0) AS CHILD_COUNT
# FROM
#     ECOLI_DATA
# ORDER BY
#     ID