WITH COLONY_GROUP AS (
    SELECT 
        ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_NUM,
        CASE 
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 1 THEN 'CRITICAL'
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 2 THEN 'HIGH'
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 3 THEN 'MEDIUM'
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 4 THEN 'LOW'
        END AS COLONY_NAME
    FROM 
        ECOLI_DATA
)

SELECT 
    ED.ID,
    CG.COLONY_NAME
FROM 
    ECOLI_DATA ED JOIN COLONY_GROUP CG ON ED.ID = CG.ID
ORDER BY 
    ED.ID;
