-- 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서
-- 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력
WITH SALES_T AS (
SELECT
    H.HISTORY_ID,
    C.CAR_TYPE,
    CASE
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE NULL
    END AS 'DURATION_TYPE',
    C.DAILY_FEE,
    DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS 'USED_DAY'
FROM
    CAR_RENTAL_COMPANY_CAR C
JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON
    C.CAR_ID = H.CAR_ID AND
    C.CAR_TYPE = '트럭'
)

SELECT
    T.HISTORY_ID,
    ROUND(T.DAILY_FEE * T.USED_DAY * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100) AS 'FEE'
    # ROUND(T.DAILY_FEE * T.USED_DAY * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM
    SALES_T T
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON
    T.CAR_TYPE = P.CAR_TYPE AND
    T.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, T.HISTORY_ID DESC