WITH JULY_SALES AS (
    SELECT
        FLAVOR,
        SUM(TOTAL_ORDER) AS 'TOTAL_ORDER'
    FROM
        JULY
    GROUP BY FLAVOR
),
FIRST_HALF_SALES AS (
    SELECT
        FH.FLAVOR,
        FH.TOTAL_ORDER + JS.TOTAL_ORDER AS 'TOTAL_ORDER'
    FROM
        FIRST_HALF FH
    JOIN
        JULY_SALES JS
    ON
        FH.FLAVOR = JS.FLAVOR
)

SELECT
    FLAVOR
FROM 
    FIRST_HALF_SALES
ORDER BY 
    TOTAL_ORDER DESC
LIMIT 3;
