WITH FILTERED_USER AS (
    SELECT WRITER_ID, SUM(PRICE) AS 'TOTAL_SALES'
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)

SELECT
    UGU.USER_ID,
    UGU.NICKNAME,
    FU.TOTAL_SALES
FROM
    USED_GOODS_USER UGU JOIN FILTERED_USER FU ON UGU.USER_ID = FU.WRITER_ID
ORDER BY FU.TOTAL_SALES;