WITH SALE_INFO AS (
    SELECT
        WRITER_ID,
        SUM(PRICE) AS SALES
    FROM
        USED_GOODS_BOARD
    WHERE
        STATUS = 'DONE'
    GROUP BY
        WRITER_ID
    HAVING
        SUM(PRICE) >= 700000
)

SELECT
    UGU.USER_ID,
    UGU.NICKNAME,
    SI.SALES AS TOTAL_SALES
FROM
    USED_GOODS_USER UGU
JOIN
    SALE_INFO SI ON UGU.USER_ID = SI.WRITER_ID
ORDER BY
    TOTAL_SALES;
