WITH Most_Active_Member AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    FETCH FIRST 1 ROWS ONLY
)
SELECT
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM
    MEMBER_PROFILE MP
JOIN
    REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE
    RR.MEMBER_ID IN (SELECT MEMBER_ID FROM Most_Active_Member)
ORDER BY
    RR.REVIEW_DATE, RR.REVIEW_TEXT;
