SELECT
    C.ID,
    C.GENOTYPE,
    P.GENOTYPE AS 'PARENT_GENOTYPE'
FROM
    ECOLI_DATA P JOIN ECOLI_DATA C ON P.ID = C.PARENT_ID
WHERE
    BIN(P.GENOTYPE & C.GENOTYPE) = BIN(P.GENOTYPE)
ORDER BY C.ID;