WITH RENTAL_COUNT AS (
    SELECT
        CAR_ID,
        EXTRACT(MONTH FROM START_DATE) AS MONTH,
        COUNT(*) AS RECORDS
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
    GROUP BY
        CAR_ID, EXTRACT(MONTH FROM START_DATE)
),
FILTERED_CARS AS (
    SELECT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
    GROUP BY
        CAR_ID
    HAVING
        COUNT(*) >= 5
)
SELECT
    RC.MONTH,
    RC.CAR_ID,
    RC.RECORDS
FROM
    RENTAL_COUNT RC
JOIN
    FILTERED_CARS FC ON RC.CAR_ID = FC.CAR_ID
ORDER BY
    RC.MONTH ASC,
    RC.CAR_ID DESC;
