WITH YEAR_DEV_MAX AS (
SELECT
    YEAR(DIFFERENTIATION_DATE) AS 'YEAR',
    MAX(SIZE_OF_COLONY) AS 'SIZE_OF_COLONY'
FROM
    ECOLI_DATA
GROUP BY
    YEAR(DIFFERENTIATION_DATE)
)

SELECT
    YEAR(ED.DIFFERENTIATION_DATE) AS 'YEAR',
    YDM.SIZE_OF_COLONY - ED.SIZE_OF_COLONY AS 'YEAR_DEV',
    ED.ID
FROM
    ECOLI_DATA ED
JOIN
    YEAR_DEV_MAX YDM
ON
    YEAR(ED.DIFFERENTIATION_DATE) = YDM.YEAR
ORDER BY
    YEAR, YEAR_DEV;