WITH SEDAN AS(
    SELECT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_CAR
    WHERE
        CAR_TYPE = '세단'
)

SELECT
    DISTINCT CCRH.CAR_ID AS CAR_ID
FROM
    SEDAN S
JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CCRH ON S.CAR_ID = CCRH.CAR_ID
WHERE
    EXTRACT(MONTH FROM CCRH.START_DATE) = 10
ORDER BY
    CAR_ID DESC;