-- 코드를 작성해주세요
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI NATURAL JOIN FISH_NAME_INFO FNI
WHERE FI.FISH_TYPE IN
(
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)
ORDER BY ID
