-- 코드를 입력하세요
SELECT ugb.TITLE, ugb.BOARD_ID, ugr.REPLY_ID, ugr.WRITER_ID, ugr.CONTENTS, TO_CHAR(ugr.CREATED_DATE, 'yyyy-mm-dd') CREADTED_DATE
FROM USED_GOODS_BOARD ugb, USED_GOODS_REPLY ugr
WHERE ugb.BOARD_ID = ugr.BOARD_ID
    AND ugb.CREATED_DATE BETWEEN TO_DATE('2022-10-01', 'yyyy-mm-dd') AND TO_DATE('2022-10-31', 'yyyy-mm-dd')
ORDER BY ugr.CREATED_DATE, ugb.TITLE;