WITH SALE_INFO AS (
    SELECT
        BOOK_ID,
        SUM(SALES) AS SALES
    FROM
        BOOK_SALES
    WHERE
        TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
    GROUP BY
        BOOK_ID
)

SELECT
    B.CATEGORY,
    SUM(SI.SALES) AS TOTAL_SALES
FROM
    BOOK B
JOIN
    SALE_INFO SI ON B.BOOK_ID = SI.BOOK_ID
GROUP BY
    B.CATEGORY
ORDER BY
    B.CATEGORY;